// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Fiverr gig title generator AI agent.
 *
 * - generateGigTitle - A function that handles the gig title generation process.
 * - GenerateGigTitleInput - The input type for the generateGigTitle function.
 * - GenerateGigTitleOutput - The return type for the generateGigTitle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateGigTitleInputSchema = z.object({
  mainKeyword: z.string().describe('The main keyword for the Fiverr gig.'),
});
export type GenerateGigTitleInput = z.infer<typeof GenerateGigTitleInputSchema>;

const GenerateGigTitleOutputSchema = z.object({
  gigTitle: z.string().describe('The generated gig title optimized for Fiverr.'),
});
export type GenerateGigTitleOutput = z.infer<typeof GenerateGigTitleOutputSchema>;

export async function generateGigTitle(input: GenerateGigTitleInput): Promise<GenerateGigTitleOutput> {
  return generateGigTitleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateGigTitlePrompt',
  input: {schema: GenerateGigTitleInputSchema},
  output: {schema: GenerateGigTitleOutputSchema},
  prompt: `You are an expert in creating highly optimized Fiverr gig titles.

  Based on the main keyword provided, generate a compelling and effective gig title that follows Fiverr best practices for search optimization and click-through rate.

  Main Keyword: {{{mainKeyword}}}`,
});

const generateGigTitleFlow = ai.defineFlow(
  {
    name: 'generateGigTitleFlow',
    inputSchema: GenerateGigTitleInputSchema,
    outputSchema: GenerateGigTitleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
