
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Fiverr gig title generator AI agent.
 *
 * - generateGigTitle - A function that handles the gig title generation process.
 */

import {ai} from '@/ai/genkit';
import type { GenerateGigTitleInput, GenerateGigTitleOutput } from '@/ai/schemas/gig-generation-schemas';
import { GenerateGigTitleInputSchema, GenerateGigTitleOutputSchema } from '@/ai/schemas/gig-generation-schemas';


export async function generateGigTitle(input: GenerateGigTitleInput): Promise<GenerateGigTitleOutput> {
  return generateGigTitleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateGigTitlePrompt',
  input: {schema: GenerateGigTitleInputSchema},
  output: {schema: GenerateGigTitleOutputSchema},
  prompt: `You are an expert in creating highly optimized Fiverr gig titles.

  Based on the main keyword provided, generate a compelling and effective gig title that follows Fiverr best practices for search optimization and click-through rate.

  Main Keyword: {{{mainKeyword}}}

  IMPORTANT: Ensure the generated gig title is unique and varied each time, even for the same input keyword.`,
});

const generateGigTitleFlow = ai.defineFlow(
  {
    name: 'generateGigTitleFlow',
    inputSchema: GenerateGigTitleInputSchema,
    outputSchema: GenerateGigTitleOutputSchema,
  },
  async (input: GenerateGigTitleInput) => {
    const {output} = await prompt(input);
    return output!;
  }
);
