
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to suggest pricing for three service packages on Fiverr based on competitor analysis.
 *
 * - suggestPackagePricing - A function that suggests pricing for Fiverr gig packages.
 * - SuggestPackagePricingInput - The input type for the suggestPackagePricing function.
 * - SuggestPackagePricingOutput - The return type for the suggestPackagePricing function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPackagePricingInputSchema = z.object({
  keyword: z.string().describe('The main keyword for the Fiverr gig.'),
});
export type SuggestPackagePricingInput = z.infer<typeof SuggestPackagePricingInputSchema>;

const SuggestPackagePricingOutputSchema = z.object({
  basic: z.number().describe('Suggested price for the basic package.'),
  standard: z.number().describe('Suggested price for the standard package.'),
  premium: z.number().describe('Suggested price for the premium package.'),
});
export type SuggestPackagePricingOutput = z.infer<typeof SuggestPackagePricingOutputSchema>;

// New schema for the prompt's input, including fetched prices
const PricingPromptInputSchema = SuggestPackagePricingInputSchema.extend({
  basicPrice: z.number().describe('The fetched basic price from competitor analysis.'),
  standardPrice: z.number().describe('The fetched standard price from competitor analysis.'),
  premiumPrice: z.number().describe('The fetched premium price from competitor analysis.'),
});
type PricingPromptInput = z.infer<typeof PricingPromptInputSchema>;


export async function suggestPackagePricing(input: SuggestPackagePricingInput): Promise<SuggestPackagePricingOutput> {
  return suggestPackagePricingFlow(input);
}

const analyzeCompetitorGigs = ai.defineTool({
  name: 'analyzeCompetitorGigs',
  description: 'Analyzes competitor gigs on Fiverr to determine appropriate pricing for different service packages.',
  inputSchema: z.object({ // Tool's input schema remains the same
    keyword: z.string().describe('The main keyword for the Fiverr gig.'),
  }),
  outputSchema: z.object({
    basic: z.number().describe('The average price of the basic package from competitor gigs.'),
    standard: z.number().describe('The average price of the standard package from competitor gigs.'),
    premium: z.number().describe('The average price of the premium package from competitor gigs.'),
  }),
},
async (input) => {
  // Placeholder implementation: return some dummy prices.
  // In a real implementation, this tool would analyze real Fiverr gigs and return more meaningful data.
  return {
    basic: 20,
    standard: 50,
    premium: 100,
  };
});

const pricingPrompt = ai.definePrompt({
  name: 'pricingPrompt',
  input: {schema: PricingPromptInputSchema}, // Use the new extended input schema
  output: {schema: SuggestPackagePricingOutputSchema},
  // tools: [], // Tool is no longer called by the LLM directly from this prompt's context
  prompt: `You are an AI pricing assistant for Fiverr gigs.
You have been provided with pricing information derived from competitor analysis for the keyword "{{{keyword}}}":
- Basic package price: {{{basicPrice}}}
- Standard package price: {{{standardPrice}}}
- Premium package price: {{{premiumPrice}}}

Based on this information, provide the suggested pricing for the three Fiverr gig packages.
Your output MUST be a JSON object strictly adhering to the following structure:
{
  "basic": <suggested_basic_price_as_number>,
  "standard": <suggested_standard_price_as_number>,
  "premium": <suggested_premium_price_as_number>
}
Ensure the values for "basic", "standard", and "premium" are the numeric prices you were provided.
`,
});

const suggestPackagePricingFlow = ai.defineFlow(
  {
    name: 'suggestPackagePricingFlow',
    inputSchema: SuggestPackagePricingInputSchema,
    outputSchema: SuggestPackagePricingOutputSchema,
  },
  async (input: SuggestPackagePricingInput): Promise<SuggestPackagePricingOutput> => {
    // Step 1: Call the tool to get competitor pricing
    const competitorPricing = await analyzeCompetitorGigs({ keyword: input.keyword });

    // Step 2: Prepare input for the pricingPrompt
    const promptInput: PricingPromptInput = {
      keyword: input.keyword,
      basicPrice: competitorPricing.basic,
      standardPrice: competitorPricing.standard,
      premiumPrice: competitorPricing.premium,
    };

    // Step 3: Call the prompt with the augmented input
    const {output} = await pricingPrompt(promptInput);
    
    if (!output) {
      throw new Error('Failed to get pricing suggestions from the AI model.');
    }
    return output;
  }
);

